theme: jekyll-theme-tactile
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <title>Brian's Got Skills</title>
    <link href="css/custom.css" rel="stylesheet">
<script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/36F0EB57-5B79-824D-B8EB-14B1C9349873/main.js" charset="UTF-8"></script></head>

<body>
    <nav>
        <ul>
            <li style="display:inline">About me -- </li>
            <li style="display:inline">About my skills -- </li>
            <li style="display:inline">My projects -- </li>
        </ul>
    </nav>
    <div id="mainContent">
        <hgroup>
            <h1>Programming / Networking / Security</h1>
            <h2>Brian Mooney</h2>
        </hgroup>
        <aside style="float:right; padding-bottom:6em;padding-right:2em;">
            <ul>
                <li><a href="#">Link to a related page</a></li>
                <li><a href="#">Link to a related page</a></li>
            </ul>
        </aside>
        <article>
            <h2>Me</h2>
            <!--- <img src="me.jpg" alt="ME" style="width:304px;height:228px;"> --->
            <p>JAVA</p>
            <p>PYTHON</p>
            <p>HTML, CSS, PHP</p>
            <p>VISUAL BASIC</p>
            <p>NETWORKING</p>
            <p>SECURITY</p>
            <p>What do I like besides computers? Brewing Kombucha and Jun, baseball and soccer</p>
        </article>
        <footer>
            <h4>Brian Mooney</h4>
            <address>ASUMH<br/> Mtn. Home, AR 72653</address>
        </footer>
    </div>
</body>
